// <auto-generated />
using System;
using ASI.Basecode.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASI.Basecode.Data.Migrations
{
    [DbContext(typeof(AsiBasecodeDBContext))]
    [Migration("20260213070054_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASI.Basecode.Data.Models.CheckIn", b =>
                {
                    b.Property<int>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInId"));

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PaymentAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CheckInId");

                    b.HasIndex("CheckInTime");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.HasIndex("CheckInTime", "CheckOutTime");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("ASI.Basecode.Data.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime?>("CancelledTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReservationId");

                    b.HasIndex("Status");

                    b.HasIndex("SeatId", "ReservationDate");

                    b.HasIndex("UserId", "ReservationDate");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ASI.Basecode.Data.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("DailyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SeatId");

                    b.HasIndex("SeatNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 400m,
                            HourlyRate = 50m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone A",
                            SeatNumber = "S-001",
                            SeatType = "VIP",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 2,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 400m,
                            HourlyRate = 50m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone A",
                            SeatNumber = "S-002",
                            SeatType = "VIP",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 3,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 400m,
                            HourlyRate = 50m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone A",
                            SeatNumber = "S-003",
                            SeatType = "VIP",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 4,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 400m,
                            HourlyRate = 50m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone A",
                            SeatNumber = "S-004",
                            SeatType = "VIP",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 5,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 400m,
                            HourlyRate = 50m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone A",
                            SeatNumber = "S-005",
                            SeatType = "VIP",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 6,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone B",
                            SeatNumber = "S-006",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 7,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone B",
                            SeatNumber = "S-007",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 8,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone B",
                            SeatNumber = "S-008",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 9,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone B",
                            SeatNumber = "S-009",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 10,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone B",
                            SeatNumber = "S-010",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 11,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone C",
                            SeatNumber = "S-011",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 12,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone C",
                            SeatNumber = "S-012",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 13,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone C",
                            SeatNumber = "S-013",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 14,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone C",
                            SeatNumber = "S-014",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 15,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 240m,
                            HourlyRate = 30m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone C",
                            SeatNumber = "S-015",
                            SeatType = "Premium",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 16,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 160m,
                            HourlyRate = 20m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone D",
                            SeatNumber = "S-016",
                            SeatType = "Regular",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 17,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 160m,
                            HourlyRate = 20m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone D",
                            SeatNumber = "S-017",
                            SeatType = "Regular",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 18,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 160m,
                            HourlyRate = 20m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone D",
                            SeatNumber = "S-018",
                            SeatType = "Regular",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 19,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 160m,
                            HourlyRate = 20m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone D",
                            SeatNumber = "S-019",
                            SeatType = "Regular",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 20,
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRate = 160m,
                            HourlyRate = 20m,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1, Zone D",
                            SeatNumber = "S-020",
                            SeatType = "Regular",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("ASI.Basecode.Data.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("MembershipEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MembershipStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("MembershipStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ASI.Basecode.Data.Models.CheckIn", b =>
                {
                    b.HasOne("ASI.Basecode.Data.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ASI.Basecode.Data.Models.Seat", "Seat")
                        .WithMany("CheckIns")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASI.Basecode.Data.Models.User", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASI.Basecode.Data.Models.Reservation", b =>
                {
                    b.HasOne("ASI.Basecode.Data.Models.Seat", "Seat")
                        .WithMany("Reservations")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASI.Basecode.Data.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASI.Basecode.Data.Models.Seat", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ASI.Basecode.Data.Models.User", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
